name: Frontend-Unit-Test
on: [push, pull_request]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress runs
        uses: cypress-io/github-action@v1
        with:
          record: false
          start: npm run test
          working-directory: ./
          headless: true
        env:
          CYPRESS_RECORD_KEY: 5c30091a-3557-4bb6-8b49-b21bea4ea9c4
