name: Frontend-Unit-Test
on: [pull_request]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress runs
        uses: cypress-io/github-action@v1
        with:
          record: false
          start: npm run test
          working-directory: ./
        env:
          CYPRESS_RECORD_KEY: 5c30091a-3557-4bb6-8b49-b21bea4ea9c4

      - name: Checking if the tests succeeded
        if: ${{ success() }}
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            **Test Result:** Tests passes
          allow-repeats: true
      - name: Checking if the tests failed
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            **Test Result:** Tests failed
          allow-repeats: true
